 pipeline {
    agent any

    environment {
        DOCKER_HUB_USER = 'sirinebb'
    }

    stages {

        stage('Checkout') {
            steps {
                echo 'Code récupéré depuis GitHub '
            }
        }

        stage('Build Backend') {
            steps {
                sh '''
                export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
                export PATH=$JAVA_HOME/bin:$PATH
                cd backend/eureka-server && mvn clean package spring-boot:repackage -DskipTests
                '''
            }
        }

        stage('SonarQube Analysis') {
            steps {
                sh '''
                export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
                export PATH=$JAVA_HOME/bin:$PATH
                cd backend/microservices/service_user
                mvn sonar:sonar \
                  -Dsonar.host.url=http://localhost:9001 \
                  -Dsonar.login=admin \
                  -Dsonar.password=admin \
                  -DskipTests
                '''
            }
        }

        stage('Docker Build & Push') {
            steps {
                sh '''
                cd backend
                docker-compose build
                docker login -u sirinebb -p $DOCKER_PASSWORD
                for img in img-eureka img-config-server img-gateway img-user \
                  img-complaint img-contrat img-evaluation img-joboffer \
                  img-certification img-portfolio img-competence \
                  img-notification img-organization img-projects \
                  img-recommendation img-nexlance-front img-prometheus; do
                  docker tag $img sirinebb/$img:latest
                  docker push sirinebb/$img:latest
                done
                '''
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                cd backend
                docker-compose up -d
                '''
            }
        }
    }

    post {
        success {
            echo ' Pipeline réussi !'
        }
        failure {
            echo ' Pipeline échoué !'
        }
    }
}
