server.port=8761
spring.application.name=eureka-server

# Le serveur Eureka ne s'enregistre pas lui-meme
eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Desactiver le mode protection en developpement
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000

logging.level.com.netflix.eureka=WARN
logging.level.com.netflix.discovery=WARN