server.port=8765
spring.application.name=api-gateway

# ============================================================
# EUREKA CLIENT
# ============================================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# ============================================================
# SPRING CLOUD GATEWAY ? Discovery automatique via Eureka
# ============================================================
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Routes ? user-service (port 8084)
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**,/api/users/**,/api/kyc/**,/api/freelance-profiles/**,/api/admin/**
spring.cloud.gateway.routes[0].filters[0]=JwtAuthenticationFilter

# Routes — complaint-service (port 8092)
spring.cloud.gateway.routes[1].id=complaint-service
spring.cloud.gateway.routes[1].uri=lb://complaint-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/complaints/**,/api/support-messages/**
spring.cloud.gateway.routes[1].filters[0]=JwtAuthenticationFilter

# Routes — notification-service (port 9090)
# POST /api/notifications est appelé en interne par complaint-service (bypass Gateway)
# GET /api/notifications/** est appelé par le frontend via Gateway
spring.cloud.gateway.routes[2].id=notification-service
spring.cloud.gateway.routes[2].uri=lb://notification-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/notifications/**
spring.cloud.gateway.routes[2].filters[0]=JwtAuthenticationFilter

# ============================================================
# CORS GLOBAL
# ============================================================
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:4200,http://localhost:4201,http://localhost:4202
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS,PATCH
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

# ============================================================
# JWT ? m�me secret que user-service
# ============================================================
jwt.secret=NexLanceSecretKeyForJWTTokenGenerationAndValidation2026

# ============================================================
# LOGS
# ============================================================
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.tn.esprit.nexlance.apigateway=DEBUG